/**
 * Content-side AI detection helpers.
 *
 * PixivFlow primarily trusts Pixiv's official `illust_ai_type` metadata
 * (2 = AI-generated). These helpers add two zero/low-cost complements:
 *
 * 1. Tag-based detection: Pixiv works generated by AI almost always carry an
 *    explicit tag such as 生成AI / AI生成 / Generative AI. Matching those tag
 *    names costs nothing and also catches works whose `illust_ai_type` field
 *    is missing (older API payloads) or has not been classified by Pixiv yet.
 * 2. File-metadata detection (optional, per-target `aiMetadataCheck`): the
 *    main AI generators embed their parameters/software in the image file
 *    itself — Stable Diffusion writes `parameters=...` into PNG tEXt chunks,
 *    NovelAI writes its prompt into PNG/EXIF metadata. Scanning the first
 *    bytes of a downloaded page is cheap (bounded read) and does not require
 *    any pixel-level analysis or model inference.
 */

/** Normalized tag-name markers for AI-generated works. */
const AI_TAG_MARKERS = [
  '生成ai',
  'ai生成',
  'generativeai',
  'aigenerated',
  'ai-generated',
  'ai generated',
];

/** ASCII markers searched in the raw file bytes (lower-cased). */
const AI_FILE_MARKERS = [
  'novelai',
  'stable diffusion',
  'stablediffusion',
  'parameters=',
  'dreamstudio',
];

/**
 * Normalize a tag string so marker matching tolerates case, spaces, hyphens,
 * underscores and full/half-width parentheses.
 */
function normalizeTag(value: string): string {
  return value
    .toLowerCase()
    .replace(/[\s\-_()（）【】[\]・、]/g, '');
}

/**
 * True when any of the work's tags contains an AI-generation marker.
 *
 * Accepts Pixiv tag arrays (`{ name, translated_name }[]`), plain string
 * arrays, or a comma-separated string — matching how tags arrive from the
 * different API endpoints.
 */
export function isAIGeneratedByTags(work: unknown): boolean {
  let tags: unknown[] = [];
  if (work && typeof work === 'object' && Array.isArray((work as { tags?: unknown }).tags)) {
    tags = (work as { tags: unknown[] }).tags;
  } else if (Array.isArray(work)) {
    tags = work;
  }

  for (const tag of tags) {
    let candidates: string[] = [];
    if (typeof tag === 'string') {
      candidates = [tag];
    } else if (tag && typeof tag === 'object') {
      const t = tag as { name?: unknown; translated_name?: unknown };
      if (typeof t.name === 'string') candidates.push(t.name);
      if (typeof t.translated_name === 'string') candidates.push(t.translated_name);
    }
    for (const candidate of candidates) {
      const normalized = normalizeTag(candidate);
      for (const marker of AI_TAG_MARKERS) {
        if (normalized.includes(marker)) return true;
      }
    }
  }
  return false;
}

/**
 * True when the first `limit` bytes of a downloaded image file contain
 * AI-generator metadata markers (Stable Diffusion / NovelAI / ...).
 *
 * The scan is deliberately bounded: generators embed their metadata near the
 * start of the file (PNG tEXt/iTXt after IHDR, JPEG EXIF APP1), so reading a
 * couple of megabytes is enough and avoids loading whole multi-MB pages.
 */
export function detectAiFileMetadata(buffer: Buffer, limit: number = 2 * 1024 * 1024): boolean {
  if (!buffer || buffer.length === 0) return false;
  const head = buffer.subarray(0, Math.min(buffer.length, limit)).toString('latin1').toLowerCase();
  for (const marker of AI_FILE_MARKERS) {
    if (head.includes(marker)) return true;
  }
  return false;
}

/**
 * Combined helper for the illustration pipelines: an illustration is treated
 * as AI when Pixiv's official flag says so OR its tags carry an AI marker.
 * (Tag matching also covers works with missing/unknown `illust_ai_type`.)
 */
export function isAIIllustration(work: unknown): boolean {
  const illust = work as { illust_ai_type?: number } | null | undefined;
  if (illust && illust.illust_ai_type === 2) return true;
  return isAIGeneratedByTags(work);
}
