#!/usr/bin/env node
/**
 * Bake package version + release commit SHA into src/version.ts before tsc.
 * Runs as a build/prepublish step; GITHUB_SHA is provided by the release CI.
 * The committed placeholder ('dev') keeps local tests/imports working.
 */
const fs = require('node:fs');
const path = require('node:path');

const version = require('../package.json').version;
const commit = (process.env.GITHUB_SHA || process.env.GIT_COMMIT || 'dev').slice(0, 12);
const target = path.join(__dirname, '..', 'src', 'version.ts');

const content =
  '// GENERATED by scripts/write-version.js — do not edit manually.\n' +
  `export const BUILD = { version: '${version}', commit: '${commit}' };\n`;

fs.writeFileSync(target, content);
console.log(`version.ts: ${version} (commit ${commit})`);
